spring:
    mvc:
        static-path-pattern: /static/**
    application:
        name: product
    datasource:
        name: user 
        url: jdbc:mysql://127.0.0.1:3306/liepin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: wusiwei1
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker: 
        allow-request-override: false
        cache: false
        check-template-location: true
        charset: UTF-8
        content-type: text/html
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: false
        template-loader-path: classpath:/templates/
        request-context-attribute: request
        settings: 
           number_format: 0 
    redis: 
        database: 0
        host: 127.0.0.1
        port: 6379
        password: wusiwei1
        timeout: 1000
        pool: 
            max-active: 64
            max-wait: -1
            max-idle: 10
            min-idle: 0
    http: 
        multipart: 
            maxFileSize: 200Mb
            maxRequestSize: 200Mb
        
        
product:
    linuxServer:
        host: 127.0.0.1
        port: 22
        username: root
        password: 'gisjdkdke#164879'
    cloud:
        basePath: /mnt/useradd.sh
        personBaseSize: 5M
        companyBaseSize: 5G
    image:
        privateBasePath: D:/privateimage/
        publicBasePath: D:/publicimage/
        showPath: /image/ 
    file:
        privateFilePath: D:/privatefile/
        publicFilePath: D:/publicfile/
        showPath: /file/
    sms:
        smsSdkAppid: 14002998
        smsSdkKey: 4fc72036df9a
        sendUrl: sms.tencentcloudapi.com
    tengxunyun:
        secretId: AKID4t
        secretKey: pTTGpBJQJy

srs:
    server:
        host: 127.0.0.1
        port: 22
        username: root
        password: 'gisjdkdke#164879'
        recordPath: /mnt/ftp/dvr_data/
    loungeStreamVhostPath: rtmp://106.12.178.201:1995/live?vhost=v001/
      
            
#imageLoad.uploadDir.basePath=D:/privateimage D:/publicimage D:/privatefile D:/publicfile
#imageLoad.uploadDir.upLoadUuid=/image/
#  127.0.0.1
#imageLoad.uploadDir.basePath=/usr/share/privatefile/  /usr/share/publicfile/ /usr/share/privateimage/ /usr/share/publicimage/
